### ISSUE TITLE
Weihachten 2022

### ISSUE THREAD

**Issue by Riksorax** [Cielquan/holidapi#2]
Hi, ich bin gerade dabei deine Ferien API bei mir im Projekt mit einzubinden und da ist mit aufgefallen das Weihnachten 2022 ein falsches end Jahr hat.

Gruß Riksorax

**Comment by Cielquan** [comment]
Vielen Dank für den Hinweis.

Das Problem sollte nun gelöst sein. Es war sogar jedes Ferien-Enddatum falsch, was im nächsten Jahr liegt. Es war ein systematischer Fehler.

**Comment by Riksorax** [comment]
Kein Thema.

Was mir nur jetzt noch aufgefallen ist, wenn ich mir z.B. die Ferien für NW lade, werden mir nur die Ferien im Herbst und für korrekt Weihnachten geladen.

**Comment by Cielquan** [comment]
Ich vermute, dass du für das Jahr 2020 guckst?

Da die derzeit verwendeten Daten mit dem Schuljahr 20/21 anfangen (siehe `data/` Ordner im Repo), sind die Feriendaten vor den Herbstferien 2020 nicht verfügbar.

Grund dafür ist, dass ich mir die Feriendaten direkt vom Kultusministerium geholt habe (https://www.kmk.org/ferienkalender.html) und zu dem Zeitpunkt waren die ältesten verfügbaren Daten die vom Schuljar 20/21, die wie ich gerade gesehen habe jetzt z.B. nicht mehr verlinkt sind.

**Comment by Riksorax** [comment]
Ich habe es mal gerade getestet, wenn ich die Jahre 2021 2023 lade werden alle Freiern geladen und wenn ich das Jahr 2022 lade werden irgendwie nur die Herbst und Weihnachtseinträge korrekt geladen.

**Comment by Cielquan** [comment]
## Ohne Bundesland
Also bekomme für
- 2021: https://cielquan.github.io/holidAPI/api/year/2021/holidays.json
- 2022: https://cielquan.github.io/holidAPI/api/year/2022/holidays.json
- 2023: https://cielquan.github.io/holidAPI/api/year/2023/holidays.json

das ganze Ferienpaket.


2020 (https://cielquan.github.io/holidAPI/api/year/2020/holidays.json) hat wie gesagt nur Herbst und Weihnachtsferien.

## Mit Bundesland

Wenn ich nach dem Jahr auch noch auf NW filtere bekomme ich für
- 2021: https://cielquan.github.io/holidAPI/api/year/2021/state/NW/holidays.json
- 2022: https://cielquan.github.io/holidAPI/api/year/2022/state/NW/holidays.json
- 2023: https://cielquan.github.io/holidAPI/api/year/2023/state/NW/holidays.json

das ganze Ferienpaket.


2020 (https://cielquan.github.io/holidAPI/api/year/2020/state/NW/holidays.json) hat hier ebenfalls wie gesagt nur Herbst und Weihnachtsferien.

---

Kannst du mir den Link geben, unter welchem du fehlerhafte Daten bekommst?

**Comment by Riksorax** [comment]
Das hat sich mittlerweile alles geklärt, ich hatte bei mir einen kleinen Fehler.

**Comment by Cielquan** [comment]
Freut mich, dass es jetzt für dich funktioniert :)
